AWSTemplateFormatVersion: '2010-09-09'
Resources:
  TestFunction4:
    Properties:
      CodeUri: s3://test-bucket-codesmith/d742a204e36d370b35372f6644244af9
      Environment:
        Variables:
          S3_BUCKET: test-bucket-codesmith
      Handler: lambda.handler1
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
  TestFunction5:
    Properties:
      CodeUri: s3://test-bucket-codesmith/d742a204e36d370b35372f6644244af9
      Environment:
        Variables:
          S3_BUCKET: test-bucket-codesmith
      Handler: lambda.handler2
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
  TestFunction6:
    Properties:
      CodeUri: s3://test-bucket-codesmith/d742a204e36d370b35372f6644244af9
      Environment:
        Variables:
          S3_BUCKET: test-bucket-codesmith
      Handler: lambda.handler3
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
